export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  AF: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Kunduz"],
  AL: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër"],
  DZ: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  AD: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria"],
  AO: ["Luanda", "Huambo", "Lubango", "Benguela", "Malanje"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata"],
  AM: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast", "Newcastle"],
  AT: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  AZ: ["Baku", "Ganja", "Sumgait", "Mingachevir", "Lankaran"],
  BH: ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"],
  BD: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  BY: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  BE: ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège"],
  BZ: ["Belmopan", "Belize City", "San Ignacio", "Orange Walk", "Corozal"],
  BJ: ["Porto-Novo", "Cotonou", "Parakou", "Djougou", "Abomey"],
  BT: ["Thimphu", "Phuntsholing", "Paro", "Punakha", "Wangdue"],
  BO: ["Sucre", "La Paz", "Santa Cruz", "Cochabamba", "Oruro"],
  BA: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  BW: ["Gaborone", "Francistown", "Molepolole", "Serowe", "Maun"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba"],
  BN: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  BF: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora"],
  BI: ["Bujumbura", "Gitega", "Ngozi", "Rumonge", "Cankuzo"],
  CV: ["Praia", "Mindelo", "Santa Maria", "São Filipe", "Assomada"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"],
  CM: ["Yaoundé", "Douala", "Garoua", "Bamenda", "Maroua"],
  CA: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Winnipeg", "Quebec City"],
  CF: ["Bangui", "Bimbo", "Berbérati", "Bambari", "Bouar"],
  TD: ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo"],
  CL: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"],
  CN: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Hangzhou", "Nanjing"],
  CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  KM: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Moya"],
  CG: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Ouesso"],
  CR: ["San José", "Puerto Limón", "Alajuela", "Heredia", "Cartago"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  CU: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  CY: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  DJ: ["Djibouti City", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil"],
  DM: ["Roseau", "Portsmouth", "Marigot", "Saint Joseph", "Wesley"],
  DO: ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís", "Puerto Plata"],
  CD: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Bukavu"],
  EC: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Manta"],
  EG: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada"],
  SV: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Mejicanos"],
  GQ: ["Malabo", "Bata", "Ebebiyín", "Aconibe", "Luba"],
  ER: ["Asmara", "Keren", "Massawa", "Mendefera", "Assab"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"],
  SZ: ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano"],
  ET: ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Hawassa", "Bahir Dar", "Jimma", "Adama"],
  FJ: ["Suva", "Nadi", "Lautoka", "Labasa", "Levuka"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Bordeaux"],
  GA: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
  GM: ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"],
  GE: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  DE: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart", "Düsseldorf", "Leipzig"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  GD: ["St. George's", "Grenville", "Victoria", "Sauteurs", "Hillsborough"],
  GT: ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla"],
  GN: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Boké"],
  GW: ["Bissau", "Bafatá", "Gabú", "Cacheu", "Bolama"],
  GY: ["Georgetown", "Linden", "New Amsterdam", "Bartica", "Anna Regina"],
  HT: ["Port-au-Prince", "Cap-Haïtien", "Jacmel", "Les Cayes", "Gonaïves"],
  HN: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "Comayagua"],
  HU: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  IS: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær"],
  IN: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"],
  ID: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
  IR: ["Tehran", "Mashhad", "Isfahan", "Shiraz", "Tabriz"],
  IQ: ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  IL: ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  IT: ["Rome", "Milan", "Naples", "Turin", "Florence", "Bologna", "Venice"],
  CI: ["Abidjan", "Yamoussoukro", "Bouaké", "Daloa", "San-Pédro"],
  JM: ["Kingston", "Montego Bay", "Spanish Town", "May Pen", "Mandeville"],
  JP: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Nagoya", "Sapporo", "Fukuoka", "Kobe"],
  JO: ["Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba"],
  KZ: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  KI: ["Tarawa", "Betio", "Bikenibeu", "Teaoraereke", "Temwaiku"],
  KW: ["Kuwait City", "Al Ahmadi", "Hawalli", "Farwaniya", "Mishref"],
  KG: ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"],
  LA: ["Vientiane", "Luang Prabang", "Pakse", "Savannakhet", "Thakhek"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"],
  LB: ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos"],
  LS: ["Maseru", "Teyateyaneng", "Leribe", "Mafeteng", "Butha-Buthe"],
  LR: ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Voinjama"],
  LY: ["Tripoli", "Benghazi", "Misrata", "Al Bayda", "Sirte"],
  LI: ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  LU: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"],
  MG: ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa"],
  MW: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Karonga"],
  MY: ["Kuala Lumpur", "George Town", "Johor Bahru", "Kota Kinabalu", "Malacca City"],
  MV: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo"],
  ML: ["Bamako", "Sikasso", "Mopti", "Koutiala", "Kayes"],
  MT: ["Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema"],
  MH: ["Majuro", "Ebeye", "Arno", "Jaluit", "Kwajalein"],
  MR: ["Nouakchott", "Nouadhibou", "Kaédi", "Zouérat", "Atar"],
  MU: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Cancún", "Mérida"],
  FM: ["Palikir", "Weno", "Kolonia", "Tofol", "Lelu"],
  MD: ["Chișinău", "Tiraspol", "Bălți", "Bender", "Cahul"],
  MC: ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"],
  MN: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Khovd"],
  ME: ["Podgorica", "Nikšić", "Bijelo Polje", "Herceg Novi", "Cetinje"],
  MA: ["Casablanca", "Rabat", "Marrakech", "Fez", "Tangier"],
  MZ: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  MM: ["Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Bago"],
  NA: ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati"],
  NR: ["Yaren", "Boe", "Denigomodu", "Meneng", "Aiwo"],
  NP: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Birgunj"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
  NI: ["Managua", "León", "Masaya", "Tipitapa", "Granada"],
  NE: ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
  NG: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Kaduna"],
  KP: ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
  OM: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur"],
  PK: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad"],
  PW: ["Ngerulmud", "Koror", "Melekeok", "Airai", "Kayangel"],
  PS: ["Ramallah", "Gaza City", "Hebron", "Jenin", "Nablus"],
  PA: ["Panama City", "Colón", "David", "La Chorrera", "Santiago"],
  PG: ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Kokopo"],
  PY: ["Asunción", "Ciudad del Este", "Capiatá", "Encarnación", "Lambaré"],
  PE: ["Lima", "Arequipa", "Cusco", "Trujillo", "Chiclayo"],
  PH: ["Manila", "Quezon City", "Davao City", "Cebu City", "Makati"],
  PL: ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań"],
  PT: ["Lisbon", "Porto", "Braga", "Coimbra", "Funchal"],
  QA: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor"],
  RO: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  RU: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
  RW: ["Kigali", "Butare", "Gisenyi", "Ruhengeri", "Gitarama"],
  KN: ["Basseterre", "Charlestown", "Sandy Point Town", "Cayon", "Dieppe Bay Town"],
  LC: ["Castries", "Gros Islet", "Vieux Fort", "Micoud", "Soufrière"],
  VC: ["Kingstown", "Georgetown", "Chateaubelair", "Layou", "Barrouallie"],
  WS: ["Apia", "Salelologa", "Vaitele", "Faleasiu", "Fasito'otai"],
  SM: ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino"],
  ST: ["São Tomé", "Santo António", "Neves", "Trindade", "Santana"],
  SA: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk"],
  SN: ["Dakar", "Touba", "Thiès", "Saint-Louis", "Kaolack"],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  SC: ["Victoria", "Beau Vallon", "Anse Royale", "La Digue", "Praslin"],
  SL: ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  SG: ["Singapore"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  SB: ["Honiara", "Auki", "Gizo", "Kirakira", "Buala"],
  SO: ["Mogadishu", "Hargeisa", "Kismayo", "Baidoa", "Burao"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon"],
  SS: ["Juba", "Malakal", "Wau", "Bor", "Yei"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga"],
  LK: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  SD: ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "Nyala"],
  SR: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Brokopondo", "Moengo"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  CH: ["Zürich", "Geneva", "Basel", "Bern", "Lausanne"],
  SY: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  TW: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan"],
  TJ: ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan"],
  TZ: ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Zanzibar City"],
  TH: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen"],
  TL: ["Dili", "Baucau", "Same", "Suai", "Maliana"],
  TG: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Palimé"],
  TO: ["Nuku'alofa", "Neiafu", "Pangai", "Haveluloto", "Mu'a"],
  TT: ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin"],
  TN: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  TM: ["Ashgabat", "Turkmenabat", "Dashoguz", "Mary", "Balkanabat"],
  TV: ["Funafuti", "Asau", "Savave", "Kulia", "Tanrake"],
  UG: ["Kampala", "Gulu", "Lira", "Jinja", "Mbale"],
  UA: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah"],
  GB: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Liverpool", "Bristol", "Edinburgh"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Boston"],
  UY: ["Montevideo", "Salto", "Paysandú", "Rivera", "Maldonado"],
  UZ: ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Andijan"],
  VU: ["Port Vila", "Luganville", "Norsup", "Sola", "Isangel"],
  VE: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Ciudad Guayana"],
  VN: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Nha Trang"],
  YE: ["Sana'a", "Aden", "Taiz", "Hodeidah", "Mukalla"],
  ZM: ["Lusaka", "Ndola", "Kitwe", "Kabwe", "Chingola"],
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
};
