/**
 * Centralized skill/category definitions for HustleX
 * Comprehensive worldwide skills organized by industry groups
 */

export interface SkillCategory {
  group: string;
  icon: string;
  skills: string[];
}

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    group: "Software & Web Development",
    icon: "Code2",
    skills: [
      "Software Development", "Web Development", "Full Stack Development",
      "Frontend Development", "Backend Development", "API Development",
      "Microservices Architecture", "E-commerce Development", "CMS Development",
      "WordPress Development", "Shopify Development", "Magento Development",
      "WooCommerce Development", "SaaS Development", "Progressive Web Apps",
      "Web Accessibility", "Web Performance Optimization", "Web Components",
      "Single Page Applications", "Server-Side Rendering", "Static Site Generation",
      "Headless CMS", "Strapi Development", "Drupal Development", "Joomla Development",
      "PrestaShop Development", "BigCommerce Development", "Squarespace Development",
      "Wix Development", "Webflow Development", "Chrome Extension Development",
      "Browser Extension Development", "Web Scraping", "Web Automation",
      "OAuth & Authentication", "Payment Gateway Integration",
    ],
  },
  {
    group: "Mobile Development",
    icon: "Smartphone",
    skills: [
      "Mobile App Development", "iOS Development", "Android Development",
      "React Native Development", "Flutter Development", "Cross-Platform Development",
      "Mobile Game Development", "Mobile UI/UX Design", "Kotlin Multiplatform",
      "SwiftUI Development", "Jetpack Compose", "App Store Optimization",
      "Mobile Payment Integration", "Push Notification Services",
      "Mobile Analytics", "Mobile Security", "Mobile App Testing",
      "WatchOS Development", "Wear OS Development", "iPad App Development",
      "Tablet App Development", "Mobile Backend as a Service",
    ],
  },
  {
    group: "Programming Languages",
    icon: "FileCode2",
    skills: [
      "JavaScript", "TypeScript", "Python", "Java", "C#", "C++", "C",
      "Go", "Rust", "Swift", "Kotlin", "Ruby", "PHP", "Perl",
      "Scala", "R", "MATLAB", "Julia", "Dart", "Lua", "Haskell",
      "Erlang", "Elixir", "Clojure", "F#", "Visual Basic", "Objective-C",
      "Assembly Language", "Fortran", "COBOL", "Pascal", "Delphi",
      "Groovy", "Tcl", "Prolog", "Scheme", "D Language", "Nim",
      "Zig", "Crystal", "OCaml", "Ada", "Apex", "ABAP",
      "Bash/Shell Scripting", "PowerShell Scripting", "Solidity", "Vyper",
      "Move (Blockchain)", "Cairo (Blockchain)",
    ],
  },
  {
    group: "Frameworks & Libraries",
    icon: "Layers",
    skills: [
      "React", "Next.js", "Vue.js", "Nuxt.js", "Angular", "Svelte", "SvelteKit",
      "Solid.js", "Remix", "Astro", "Qwik", "Alpine.js", "Ember.js", "Backbone.js",
      "Redux", "Zustand", "MobX", "Recoil", "Jotai", "XState",
      "Tailwind CSS", "Bootstrap", "Material UI", "Chakra UI", "Ant Design",
      "Styled Components", "CSS Modules", "Sass/SCSS", "Less", "Stylus",
      "Node.js", "Express", "NestJS", "Fastify", "Koa", "Hapi",
      "Django", "Flask", "FastAPI", "Tornado", "Pyramid",
      "Spring Boot", "Spring MVC", "Hibernate", "Jakarta EE",
      "Ruby on Rails", "Sinatra", "Hanami",
      "Laravel", "Symfony", "CodeIgniter", "CakePHP", "Zend Framework",
      "ASP.NET Core", "ASP.NET MVC", "Blazor", "MAUI",
      "Gin", "Echo", "Fiber", "Actix Web",
      "Rocket (Rust)", "Axum", "Warp",
      "Phoenix (Elixir)", "Play Framework",
      ".NET Core", ".NET Framework", "Entity Framework",
      "jQuery", "D3.js", "Three.js", "Chart.js", "GSAP", "Anime.js",
      "Lodash", "Moment.js", "Day.js", "Axios", "SWR", "React Query",
      "Prisma", "Sequelize", "TypeORM", "Knex.js", "Mongoose", "Drizzle ORM",
      "tRPC", "gRPC", "Socket.IO", "WebSocket", "GraphQL", "Apollo",
      "REST API Design", "OpenAPI/Swagger", "Postman",
    ],
  },
  {
    group: "Databases & Storage",
    icon: "Database",
    skills: [
      "SQL", "NoSQL", "MongoDB", "PostgreSQL", "MySQL", "MariaDB", "SQLite",
      "Oracle Database", "Microsoft SQL Server", "IBM DB2",
      "Redis", "Memcached", "Cassandra", "CouchDB", "DynamoDB",
      "Firebase Firestore", "Firebase Realtime Database", "Supabase",
      "PlanetScale", "CockroachDB", "TiDB", "ScyllaDB", "Neo4j",
      "ArangoDB", "Fauna", "InfluxDB", "TimescaleDB", "ClickHouse",
      "Elasticsearch", "Apache Solr", "Meilisearch", "Algolia",
      "Apache Kafka", "RabbitMQ", "Apache Pulsar", "NATS",
      "Database Administration", "Database Design", "Database Optimization",
      "Data Migration", "Data Warehousing", "ETL Pipelines",
      "Stored Procedures", "Database Replication", "Sharding",
      "Object Storage", "File System Management", "CDN Configuration",
    ],
  },
  {
    group: "Data Science & AI",
    icon: "Brain",
    skills: [
      "Data Science", "Machine Learning & AI", "Deep Learning",
      "Natural Language Processing", "Computer Vision", "AI Prompt Engineering",
      "Business Intelligence", "Data Analysis", "Data Visualization",
      "Data Engineering", "Big Data Processing", "Statistical Analysis",
      "Predictive Analytics", "AI Model Fine-Tuning",
      "TensorFlow", "PyTorch", "Keras", "Scikit-learn", "Pandas", "NumPy",
      "SciPy", "Matplotlib", "Seaborn", "Plotly", "Tableau", "Power BI",
      "Apache Spark", "Hadoop", "Apache Flink", "Dask",
      "Reinforcement Learning", "Generative AI", "Large Language Models",
      "ChatGPT Integration", "LangChain", "Hugging Face", "OpenAI API",
      "Stable Diffusion", "Midjourney", "GPT-4 API", "Claude API",
      "MLOps", "Model Deployment", "Feature Engineering",
      "A/B Testing", "Experimental Design", "Bayesian Statistics",
      "Time Series Analysis", "Regression Analysis", "Classification",
      "Clustering", "Anomaly Detection", "Recommendation Systems",
      "Speech Recognition", "Image Recognition", "Object Detection",
      "Sentiment Analysis", "Text Mining", "Data Labeling",
      "Jupyter", "Google Colab", "Anaconda",
    ],
  },
  {
    group: "DevOps & Cloud",
    icon: "Cloud",
    skills: [
      "DevOps Engineering", "Cloud Computing", "AWS Services", "Azure Cloud",
      "Google Cloud Platform", "DigitalOcean", "Linode", "Vultr", "Heroku",
      "Cloudflare", "Vercel", "Netlify", "Fly.io", "Railway",
      "Kubernetes", "Docker", "Docker Compose", "Helm", "Istio",
      "CI/CD Pipelines", "GitHub Actions", "GitLab CI", "Jenkins",
      "CircleCI", "Travis CI", "Azure DevOps", "Bitbucket Pipelines",
      "Infrastructure as Code", "Terraform", "Pulumi", "CloudFormation",
      "Ansible", "Chef", "Puppet", "SaltStack", "Vagrant",
      "Site Reliability Engineering", "Serverless Architecture",
      "AWS Lambda", "Azure Functions", "Google Cloud Functions",
      "Load Balancing", "Auto Scaling", "DNS Management",
      "Nginx", "Apache HTTP Server", "Caddy", "HAProxy", "Traefik",
      "Linux Administration", "Windows Server", "macOS Server",
      "Bash Scripting", "Shell Scripting", "System Administration",
      "Monitoring & Logging", "Prometheus", "Grafana", "Datadog",
      "New Relic", "Splunk", "ELK Stack", "Sentry",
      "Git", "GitHub", "GitLab", "Bitbucket", "Version Control",
      "Release Management", "Blue-Green Deployment", "Canary Deployment",
      "Container Orchestration", "Service Mesh", "API Gateway",
    ],
  },
  {
    group: "Cybersecurity",
    icon: "Shield",
    skills: [
      "Cybersecurity", "Penetration Testing", "Network Security",
      "Security Auditing", "Ethical Hacking", "Vulnerability Assessment",
      "Application Security", "Cloud Security", "IoT Security",
      "Cryptography", "Encryption", "SSL/TLS", "PKI",
      "Firewall Management", "IDS/IPS", "SIEM",
      "Incident Response", "Digital Forensics", "Malware Analysis",
      "Threat Modeling", "Risk Assessment", "Security Compliance",
      "OWASP", "SOC 2", "ISO 27001", "HIPAA Compliance",
      "PCI DSS Compliance", "GDPR Compliance", "Zero Trust Architecture",
      "Identity & Access Management", "Multi-Factor Authentication",
      "Security Operations Center", "Bug Bounty Hunting",
      "Red Team Operations", "Blue Team Defense", "Purple Team",
      "Web Application Firewall", "DDoS Protection",
    ],
  },
  {
    group: "Blockchain & Web3",
    icon: "Link",
    skills: [
      "Blockchain & Cryptocurrency", "Smart Contract Development",
      "Web3 Development", "NFT Development", "DeFi Development",
      "Solidity", "Vyper", "Hardhat", "Truffle", "Foundry",
      "Ethereum", "Polygon", "BNB Chain", "Solana", "Avalanche",
      "Cardano", "Polkadot", "Cosmos", "Near Protocol",
      "Hyperledger", "Corda", "Stellar", "Ripple",
      "DAO Development", "Token Economics", "ICO/IDO Development",
      "Crypto Wallet Development", "Metamask Integration",
      "IPFS", "Chainlink Oracles", "The Graph",
      "Blockchain Consulting", "Crypto Trading Bot Development",
      "Cross-Chain Development", "Layer 2 Solutions",
    ],
  },
  {
    group: "IoT & Embedded",
    icon: "Cpu",
    skills: [
      "IoT Development", "Embedded Systems", "Firmware Development",
      "Arduino", "Raspberry Pi", "ESP32", "STM32", "ARM Cortex",
      "RTOS", "FreeRTOS", "Zephyr OS",
      "MQTT", "CoAP", "Zigbee", "Z-Wave", "LoRaWAN", "NB-IoT",
      "PCB Design", "Circuit Design", "Microcontroller Programming",
      "Sensor Integration", "Edge Computing", "Industrial IoT",
      "Home Automation", "Smart Home Development", "Wearable Technology",
      "Robotics", "Drone Development", "Autonomous Systems",
      "FPGA Programming", "VHDL", "Verilog", "Digital Signal Processing",
    ],
  },
  {
    group: "Game Development",
    icon: "Gamepad2",
    skills: [
      "Game Development", "Unity Game Engine", "Unreal Engine",
      "Godot Engine", "GameMaker Studio", "Construct",
      "Game Design", "Game Art & Animation", "Game Audio",
      "Level Design", "Game Narrative Design", "Game Economy Design",
      "VR/AR Development", "Metaverse Development", "Mixed Reality",
      "Multiplayer Networking", "Game Physics", "Game AI",
      "2D Game Development", "3D Game Development",
      "Mobile Game Development", "PC Game Development", "Console Game Development",
      "Game Modding", "Game Testing", "Game Localization",
      "Pixel Art", "Sprite Animation", "Procedural Generation",
      "Steam SDK Integration", "Epic Games Store",
    ],
  },
  {
    group: "UI/UX & Design",
    icon: "Palette",
    skills: [
      "UI/UX Design", "Graphic Design", "Motion Graphics",
      "3D Animation", "3D Modeling", "Product Design",
      "Design Systems", "Wireframing & Prototyping", "User Research",
      "Interaction Design", "Brand Identity Design", "Illustration",
      "Infographic Design", "Presentation Design",
      "Figma", "Adobe XD", "Sketch", "InVision", "Framer",
      "Photoshop", "Illustrator", "InDesign", "Adobe Creative Suite",
      "Canva", "CorelDRAW", "Affinity Designer", "Affinity Photo",
      "Blender", "Maya", "Cinema 4D", "3ds Max", "ZBrush",
      "After Effects", "Premiere Pro", "DaVinci Resolve",
      "Print Design", "Logo Design", "Typography",
      "Color Theory", "Layout Design", "Icon Design",
      "Service Design", "Design Thinking", "Accessibility Design",
      "Responsive Design", "Mobile-First Design", "Dark Mode Design",
      "UX Writing", "Information Architecture", "Usability Testing",
      "Heatmap Analysis", "A/B Testing Design", "Conversion Design",
      "Lottie Animation", "Rive Animation",
    ],
  },
  {
    group: "Photography, Video & Audio",
    icon: "Camera",
    skills: [
      "Photography", "Videography", "Video Editing", "Video Production",
      "Animation & VFX", "Drone Photography", "Aerial Videography",
      "Music Production", "Audio Production", "Sound Design",
      "Voice Over", "Podcast Production", "Mixing & Mastering",
      "Music Composition", "Beat Making", "Songwriting",
      "Live Streaming", "OBS Studio", "Streamlabs",
      "Color Grading", "Compositing", "Green Screen",
      "Product Photography", "Portrait Photography", "Wedding Photography",
      "Real Estate Photography", "Food Photography", "Fashion Photography",
      "Photo Editing", "Photo Retouching", "Lightroom",
      "Final Cut Pro", "Adobe Audition", "Logic Pro", "FL Studio",
      "Ableton Live", "Pro Tools", "GarageBand",
      "Stock Photography", "Stock Footage", "Timelapse Photography",
      "360° Photography", "360° Video",
    ],
  },
  {
    group: "Architecture & Interior",
    icon: "Building2",
    skills: [
      "Architecture", "Interior Design", "Landscape Architecture",
      "CAD & 3D Rendering", "Fashion Design", "Textile Design",
      "Industrial Design", "Packaging Design", "Exhibition Design",
      "AutoCAD", "Revit", "SketchUp", "Rhino 3D", "Lumion",
      "V-Ray Rendering", "Enscape", "Twinmotion",
      "BIM (Building Information Modeling)", "Structural Drafting",
      "MEP Design", "HVAC Design", "Plumbing Design",
      "Space Planning", "Furniture Design", "Lighting Design",
      "Kitchen & Bath Design", "Commercial Interior Design",
      "Residential Architecture", "Commercial Architecture",
      "Sustainable Design", "Green Building", "LEED Consulting",
      "Urban Design", "City Planning", "Set Design",
    ],
  },
  {
    group: "Writing & Content",
    icon: "PenTool",
    skills: [
      "Content Writing", "Technical Writing", "Copywriting",
      "Creative Writing", "Blog Writing", "Ghostwriting",
      "Grant Writing", "Resume & Cover Letter Writing",
      "Editing & Proofreading", "Scriptwriting", "Academic Writing",
      "Journalism", "Feature Writing", "Investigative Journalism",
      "Whitepaper Writing", "Case Study Writing", "Proposal Writing",
      "Speech Writing", "Songwriting", "Poetry",
      "E-book Writing", "Self-Publishing", "Book Editing",
      "Newsletter Writing", "Email Copywriting", "Landing Page Copy",
      "Ad Copy", "Slogan Writing", "Tagline Creation",
      "Legal Writing", "Medical Writing", "Science Writing",
      "Travel Writing", "Food Writing", "Sports Writing",
      "UX Writing", "Microcopy", "Content Strategy",
      "Editorial Planning", "Style Guide Development",
      "Proofreading", "Fact-Checking", "Indexing",
    ],
  },
  {
    group: "Translation & Languages",
    icon: "Languages",
    skills: [
      "Translation & Localization", "English Translation",
      "Amharic Translation", "Arabic Translation", "French Translation",
      "Chinese Translation", "Spanish Translation", "German Translation",
      "Japanese Translation", "Korean Translation", "Portuguese Translation",
      "Russian Translation", "Italian Translation", "Hindi Translation",
      "Turkish Translation", "Swahili Translation", "Tigrinya Translation",
      "Oromo Translation", "Somali Translation", "Yoruba Translation",
      "Zulu Translation", "Dutch Translation", "Polish Translation",
      "Vietnamese Translation", "Thai Translation", "Indonesian Translation",
      "Malay Translation", "Filipino Translation", "Urdu Translation",
      "Bengali Translation", "Tamil Translation", "Telugu Translation",
      "Interpretation Services", "Subtitling & Captioning", "Transcription",
      "Simultaneous Interpretation", "Consecutive Interpretation",
      "Sign Language Interpretation", "Audio Description",
      "Software Localization", "Website Localization", "Game Localization",
      "Legal Translation", "Medical Translation", "Technical Translation",
      "Literary Translation", "Certified Translation",
    ],
  },
  {
    group: "Digital Marketing & SEO",
    icon: "Megaphone",
    skills: [
      "Digital Marketing", "SEO", "SEM", "Social Media Marketing",
      "Email Marketing", "Content Marketing", "Influencer Marketing",
      "PPC Advertising", "Affiliate Marketing", "Marketing Analytics",
      "Conversion Rate Optimization", "Growth Hacking",
      "Community Management", "Brand Marketing", "Viral Marketing",
      "Google Ads", "Facebook Ads", "Instagram Ads", "TikTok Ads",
      "LinkedIn Ads", "Twitter Ads", "YouTube Ads", "Pinterest Ads",
      "Snapchat Ads", "Reddit Ads", "Quora Advertising",
      "Facebook Business Manager", "Meta Ads Manager",
      "Google Analytics", "Google Tag Manager", "Google Search Console",
      "SEMrush", "Ahrefs", "Moz", "Screaming Frog",
      "HubSpot", "Mailchimp", "ConvertKit", "ActiveCampaign",
      "Klaviyo", "Brevo (Sendinblue)",
      "Marketing Automation", "CRM Marketing",
      "Retargeting", "Remarketing", "Lookalike Audiences",
      "Landing Page Optimization", "Funnel Building",
      "Webinar Marketing", "Podcast Marketing",
      "SMS Marketing", "WhatsApp Marketing",
      "E-commerce Marketing", "Amazon Marketing",
      "App Store Optimization", "YouTube SEO",
    ],
  },
  {
    group: "Sales & Business Development",
    icon: "TrendingUp",
    skills: [
      "Sales & Business Development", "Lead Generation",
      "Business Strategy", "Market Research", "Competitive Analysis",
      "Business Plan Writing", "Startup Consulting", "Franchise Consulting",
      "E-commerce Strategy", "Pricing Strategy",
      "B2B Sales", "B2C Sales", "Enterprise Sales", "SaaS Sales",
      "Inside Sales", "Field Sales", "Channel Sales",
      "Sales Management", "Sales Operations", "Sales Enablement",
      "Salesforce CRM", "HubSpot CRM", "Zoho CRM", "Pipedrive",
      "Cold Calling", "Cold Emailing", "Appointment Setting",
      "Negotiation", "Closing Techniques", "Account Management",
      "Key Account Management", "Customer Retention",
      "Business Development", "Partnership Development",
      "Strategic Alliances", "Joint Ventures",
      "International Business", "Import/Export",
      "Retail Management", "Merchandising",
      "Pitch Deck Creation", "Investor Relations",
    ],
  },
  {
    group: "Customer & Admin Support",
    icon: "Headphones",
    skills: [
      "Customer Service", "Customer Success", "Technical Support",
      "Virtual Assistant", "Data Entry", "Executive Assistance",
      "Calendar Management", "Travel Planning", "Order Processing",
      "Chat Support", "Phone Support", "Email Support",
      "Help Desk Support", "IT Support", "Remote Support",
      "Customer Experience", "Customer Onboarding",
      "Complaint Resolution", "Escalation Management",
      "Zendesk", "Freshdesk", "Intercom", "Drift", "LiveChat",
      "Office Administration", "Receptionist Services",
      "Bookkeeping", "Invoicing", "Expense Management",
      "Document Management", "Records Management",
      "Scheduling", "Meeting Coordination",
      "Transcription", "Typing", "Word Processing",
      "Excel Spreadsheets", "Google Workspace", "Microsoft Office",
    ],
  },
  {
    group: "Project & Product Management",
    icon: "KanbanSquare",
    skills: [
      "Project Management", "Product Management", "Program Management",
      "Agile Coaching", "Scrum Master", "Operations Management",
      "Process Improvement", "Risk Management", "Change Management",
      "Stakeholder Management", "Portfolio Management",
      "Waterfall Methodology", "Kanban", "Lean Management",
      "Six Sigma", "PMP Certified", "PRINCE2",
      "Jira", "Asana", "Trello", "Monday.com", "ClickUp",
      "Notion", "Confluence", "Slack", "Microsoft Teams",
      "Resource Planning", "Budget Management", "Timeline Management",
      "Vendor Management", "Procurement Management",
      "Business Process Reengineering", "Workflow Automation",
      "OKRs", "KPIs", "Roadmap Planning",
      "Product Discovery", "Product Analytics", "User Story Mapping",
      "Feature Prioritization", "Release Planning", "Sprint Planning",
      "Retrospectives", "Standup Facilitation",
    ],
  },
  {
    group: "Finance & Accounting",
    icon: "Calculator",
    skills: [
      "Financial Analysis", "Accounting", "Bookkeeping",
      "Tax Consulting", "Tax Preparation", "Payroll Management",
      "Financial Modeling", "Budgeting & Forecasting",
      "Investment Analysis", "Audit & Assurance",
      "Crypto Accounting", "Invoicing & Billing",
      "QuickBooks", "Xero", "FreshBooks", "Wave Accounting",
      "SAP Finance", "Oracle Financials", "Sage Accounting",
      "Financial Planning", "Wealth Management", "Portfolio Management",
      "Risk Analysis", "Credit Analysis", "Loan Processing",
      "Banking Operations", "Insurance Underwriting",
      "Actuarial Science", "Forensic Accounting",
      "Cost Accounting", "Managerial Accounting",
      "IFRS", "GAAP", "SOX Compliance",
      "Accounts Payable", "Accounts Receivable",
      "Financial Reporting", "VAT/GST Filing",
      "Cryptocurrency Trading", "Forex Trading",
      "Stock Market Analysis", "Options Trading",
      "Venture Capital", "Private Equity", "Crowdfunding",
    ],
  },
  {
    group: "Human Resources",
    icon: "Users",
    skills: [
      "Human Resources Management", "Recruitment", "Talent Acquisition",
      "Employee Training", "Performance Management", "HR Consulting",
      "Compensation & Benefits", "HRIS Administration",
      "Diversity & Inclusion", "Onboarding & Offboarding",
      "Employee Relations", "Labor Relations",
      "Talent Management", "Succession Planning",
      "Organizational Development", "Culture Development",
      "HR Analytics", "Workforce Planning",
      "Job Description Writing", "Interview Techniques",
      "Background Checks", "Reference Checking",
      "Employee Engagement", "Employee Surveys",
      "Benefits Administration", "401k/Pension Management",
      "Workers' Compensation", "FMLA/Leave Management",
      "Employment Law Compliance", "EEO Compliance",
      "Payroll Processing", "Time & Attendance",
      "HR Software (BambooHR, Workday, Gusto)",
      "Executive Search", "Headhunting", "Employer Branding",
    ],
  },
  {
    group: "Legal & Compliance",
    icon: "Scale",
    skills: [
      "Legal Services", "Contract Management", "Compliance Management",
      "Intellectual Property", "Corporate Law", "Employment Law",
      "Privacy & Data Protection", "Trademark Registration",
      "Legal Research", "Immigration Law",
      "Patent Filing", "Copyright Registration", "Licensing",
      "Family Law", "Criminal Law", "Civil Litigation",
      "Real Estate Law", "Tax Law", "Environmental Law",
      "International Law", "Maritime Law", "Sports Law",
      "Entertainment Law", "Healthcare Law", "Technology Law",
      "Paralegal Services", "Legal Document Preparation",
      "Contract Review", "Contract Negotiation",
      "NDAs", "Terms of Service", "Privacy Policy Drafting",
      "Regulatory Compliance", "Anti-Money Laundering",
      "KYC/AML", "Export Controls", "Sanctions Compliance",
      "Mediation", "Arbitration", "Dispute Resolution",
      "Notary Services", "Legal Translation",
    ],
  },
  {
    group: "Healthcare & Medical",
    icon: "HeartPulse",
    skills: [
      "Healthcare Services", "Nursing", "Pharmacy",
      "Medical Writing", "Telemedicine", "Medical Billing & Coding",
      "Health Informatics", "Mental Health Counseling",
      "Nutrition & Dietetics", "Physical Therapy",
      "Dental Services", "Optometry", "Veterinary Medicine",
      "Medical Research", "Clinical Research", "Clinical Trials",
      "Pharmacology", "Epidemiology", "Public Health",
      "Healthcare Administration", "Medical Practice Management",
      "Radiology", "Sonography", "Laboratory Services",
      "Emergency Medicine", "Paramedic Services",
      "Occupational Therapy", "Speech Therapy",
      "Massage Therapy", "Chiropractic", "Acupuncture",
      "Home Healthcare", "Elder Care", "Palliative Care",
      "Medical Device Development", "Biotechnology",
      "Genetics", "Genomics", "Bioinformatics",
      "Medical Illustration", "Health Education",
      "Personal Training", "Yoga Instruction", "Pilates Instruction",
      "Sports Medicine", "Athletic Training",
    ],
  },
  {
    group: "Education & Training",
    icon: "GraduationCap",
    skills: [
      "Education & Training", "Instructional Design",
      "E-Learning Development", "Curriculum Design",
      "Tutoring", "Corporate Training",
      "Language Teaching", "Test Preparation",
      "Educational Consulting", "Coaching & Mentoring",
      "Online Teaching", "Course Creation", "MOOC Development",
      "Articulate Storyline", "Adobe Captivate", "Camtasia",
      "Learning Management Systems", "Moodle", "Canvas LMS",
      "Blackboard", "Teachable", "Thinkific", "Kajabi",
      "Special Education", "Early Childhood Education",
      "STEM Education", "ESL/TEFL Teaching",
      "Academic Advising", "Student Counseling",
      "Educational Technology", "Gamification in Education",
      "Assessment Design", "Rubric Development",
      "Lesson Planning", "Classroom Management",
      "Music Teaching", "Art Teaching", "Dance Instruction",
      "Cooking Classes", "Fitness Instruction",
    ],
  },
  {
    group: "Engineering",
    icon: "Wrench",
    skills: [
      "Civil Engineering", "Mechanical Engineering",
      "Electrical Engineering", "Chemical Engineering",
      "Automobile Engineering", "Aerospace Engineering",
      "Environmental Engineering", "Structural Engineering",
      "Geotechnical Engineering", "Surveying",
      "Quality Control Engineering", "Industrial Engineering",
      "Biomedical Engineering", "Nuclear Engineering",
      "Petroleum Engineering", "Mining Engineering",
      "Marine Engineering", "Naval Architecture",
      "Telecommunications Engineering", "RF Engineering",
      "Control Systems Engineering", "Instrumentation",
      "Power Systems", "Renewable Energy Engineering",
      "Solar Energy Systems", "Wind Energy Systems",
      "HVAC Engineering", "Plumbing Engineering",
      "Fire Protection Engineering", "Acoustical Engineering",
      "Materials Science", "Nanotechnology",
      "CAD Design", "SolidWorks", "CATIA", "AutoCAD",
      "Finite Element Analysis", "CFD Analysis",
      "Project Engineering", "Process Engineering",
    ],
  },
  {
    group: "Agriculture & Environment",
    icon: "Sprout",
    skills: [
      "Farming & Agriculture", "Agricultural Engineering",
      "Veterinary Services", "Environmental Consulting",
      "Sustainability Consulting", "Renewable Energy",
      "Waste Management", "Forestry", "Wildlife Management",
      "Aquaculture", "Food Science & Technology",
      "Organic Farming", "Hydroponics", "Aquaponics",
      "Precision Agriculture", "Agricultural Drones",
      "Crop Science", "Soil Science", "Horticulture",
      "Floriculture", "Viticulture", "Beekeeping",
      "Animal Husbandry", "Dairy Farming", "Poultry Farming",
      "Agribusiness", "Agricultural Economics",
      "Food Processing", "Food Safety", "HACCP",
      "Environmental Impact Assessment", "Carbon Footprint Analysis",
      "Water Resource Management", "Irrigation Design",
      "Climate Change Analysis", "Conservation",
      "Ecology", "Biodiversity Assessment",
      "GIS & Remote Sensing", "Environmental Monitoring",
    ],
  },
  {
    group: "Real Estate & Construction",
    icon: "Home",
    skills: [
      "Real Estate Management", "Property Valuation",
      "Real Estate Marketing", "Construction Management",
      "Interior Decoration", "Facility Management", "Urban Planning",
      "Property Development", "Real Estate Investment",
      "Commercial Real Estate", "Residential Real Estate",
      "Property Management", "Tenant Relations",
      "Real Estate Photography", "Real Estate Videography",
      "Home Staging", "Home Inspection",
      "Mortgage Brokerage", "Title Services",
      "Construction Estimation", "Quantity Surveying",
      "Project Scheduling", "Building Codes & Regulations",
      "General Contracting", "Subcontractor Management",
      "Carpentry", "Plumbing", "Electrical Work",
      "Masonry", "Roofing", "Painting", "Welding",
      "Heavy Equipment Operation", "Crane Operation",
      "Demolition", "Excavation", "Landscaping",
    ],
  },
  {
    group: "Media, Events & Hospitality",
    icon: "PartyPopper",
    skills: [
      "Event Planning", "Wedding Planning", "Corporate Events",
      "Public Relations", "Journalism", "Broadcasting",
      "Social Media Management", "Hospitality Management",
      "Travel Consulting", "Tour Guiding", "Restaurant Management",
      "Catering", "Bartending", "Sommelier Services",
      "Hotel Management", "Tourism Management",
      "Airline Operations", "Cruise Ship Operations",
      "Concierge Services", "Guest Relations",
      "Conference Planning", "Trade Show Management",
      "Festival Organization", "Concert Promotion",
      "DJ Services", "Entertainment Booking",
      "Talent Management", "Artist Management",
      "Music Management", "Film Production",
      "TV Production", "Radio Production",
      "Publishing", "Newspaper & Magazine",
      "Digital Media", "Content Curation",
    ],
  },
  {
    group: "Manufacturing & Logistics",
    icon: "Factory",
    skills: [
      "Manufacturing", "Supply Chain Management", "Logistics",
      "Warehouse Management", "Procurement", "Inventory Management",
      "Printing & Publishing", "Packaging & Labeling",
      "Quality Assurance", "Lean Manufacturing",
      "Six Sigma Manufacturing", "Production Planning",
      "CNC Machining", "3D Printing", "Injection Molding",
      "Sheet Metal Fabrication", "Welding & Fabrication",
      "Textile Manufacturing", "Garment Manufacturing",
      "Electronics Manufacturing", "Semiconductor Manufacturing",
      "Pharmaceutical Manufacturing", "Food & Beverage Manufacturing",
      "Fleet Management", "Freight Forwarding",
      "Customs Brokerage", "Import/Export Compliance",
      "Last Mile Delivery", "Route Optimization",
      "Demand Forecasting", "Materials Requirement Planning",
      "Supplier Relationship Management", "Vendor Management",
      "Distribution Center Operations",
    ],
  },
  {
    group: "Transportation & Automotive",
    icon: "Truck",
    skills: [
      "Fleet Management", "Logistics Coordination",
      "Automotive Repair", "Automotive Diagnostics",
      "Auto Body Repair", "Auto Painting", "Auto Detailing",
      "Automotive Engineering", "EV Technology",
      "Aviation Maintenance", "Pilot Training",
      "Maritime Operations", "Shipping & Freight",
      "Public Transportation", "Ride-sharing Operations",
      "Delivery Services", "Courier Services",
      "Driving Instruction", "CDL Driving",
      "Traffic Engineering", "Transportation Planning",
      "Vehicle Wrapping", "Window Tinting",
    ],
  },
  {
    group: "Beauty, Fashion & Wellness",
    icon: "Sparkles",
    skills: [
      "Hairdressing", "Barbering", "Makeup Artistry",
      "Nail Art & Design", "Skincare", "Esthetics",
      "Spa Management", "Massage Therapy", "Aromatherapy",
      "Fashion Design", "Fashion Styling", "Fashion Merchandising",
      "Personal Styling", "Wardrobe Consulting", "Image Consulting",
      "Jewelry Design", "Accessory Design",
      "Cosmetic Chemistry", "Beauty Product Development",
      "Wellness Coaching", "Life Coaching",
      "Meditation Instruction", "Mindfulness Training",
      "Holistic Health", "Ayurvedic Medicine",
      "Tattoo Artistry", "Body Piercing",
      "Cosmetology", "Beauty Therapy",
      "Pattern Making", "Sewing", "Tailoring",
      "Fashion Photography", "Fashion Blogging",
    ],
  },
  {
    group: "Security & Safety",
    icon: "ShieldCheck",
    skills: [
      "Security Services", "Private Investigation",
      "Fire Safety", "Occupational Health & Safety",
      "Emergency Management", "Loss Prevention",
      "CCTV Installation & Monitoring", "Access Control Systems",
      "Alarm Systems", "Security Guard Services",
      "Executive Protection", "Event Security",
      "Cybersecurity Consulting", "Physical Security",
      "Background Investigation", "Fraud Investigation",
      "Insurance Investigation", "Claims Adjusting",
      "Disaster Recovery", "Business Continuity Planning",
      "First Aid Training", "CPR Training",
      "Firefighting", "Search & Rescue",
      "Hazardous Materials Handling", "Environmental Safety",
    ],
  },
  {
    group: "Social & Community Services",
    icon: "HeartHandshake",
    skills: [
      "Social Work", "Counseling", "Nonprofit Management",
      "Fundraising", "Community Development", "Youth Development",
      "Disability Support", "Elder Care Services",
      "Child Welfare", "Foster Care Services",
      "Domestic Violence Support", "Crisis Intervention",
      "Substance Abuse Counseling", "Rehabilitation Services",
      "Refugee Services", "Immigration Services",
      "Housing Assistance", "Food Security Programs",
      "Grant Writing", "Program Evaluation",
      "Community Outreach", "Volunteer Coordination",
      "Advocacy", "Policy Analysis",
      "Public Administration", "Government Relations",
      "International Development", "Humanitarian Aid",
    ],
  },
  {
    group: "Sports & Recreation",
    icon: "Trophy",
    skills: [
      "Personal Training", "Sports Coaching", "Athletic Training",
      "Sports Management", "Sports Marketing", "Sports Analytics",
      "Sports Medicine", "Sports Nutrition",
      "Fitness Instruction", "Group Fitness", "CrossFit Coaching",
      "Yoga Instruction", "Pilates Instruction", "Dance Instruction",
      "Martial Arts Instruction", "Swimming Instruction",
      "Ski/Snowboard Instruction", "Surfing Instruction",
      "Golf Instruction", "Tennis Coaching",
      "Referee/Umpire", "Sports Officiating",
      "Sports Photography", "Sports Broadcasting",
      "Sports Event Management", "League Management",
      "Recreation Planning", "Park Management",
      "Outdoor Adventure Guiding", "Scuba Diving Instruction",
      "Rock Climbing Instruction", "Kayaking/Canoeing Instruction",
    ],
  },
  {
    group: "Arts & Entertainment",
    icon: "Theater",
    skills: [
      "Acting", "Directing", "Producing", "Screenwriting",
      "Stand-up Comedy", "Improvisation", "Theater Production",
      "Musical Performance", "Singing", "Dancing",
      "Choreography", "DJ Services", "Music Production",
      "Painting", "Sculpture", "Ceramics", "Printmaking",
      "Digital Art", "Concept Art", "Storyboarding",
      "Calligraphy", "Tattoo Art", "Face Painting",
      "Magic & Illusion", "Circus Arts",
      "Museum Curation", "Art Gallery Management",
      "Art Restoration", "Art Appraisal", "Art Dealing",
      "Film Criticism", "Book Reviewing",
      "Entertainment Journalism", "Celebrity Management",
    ],
  },
  {
    group: "Skilled Trades",
    icon: "Hammer",
    skills: [
      "Carpentry", "Plumbing", "Electrical Work", "Welding",
      "HVAC Installation & Repair", "Masonry", "Roofing",
      "Painting & Decorating", "Flooring Installation",
      "Tile Setting", "Drywall Installation", "Insulation",
      "Glazing (Glass Work)", "Locksmithing",
      "Appliance Repair", "Small Engine Repair",
      "Elevator Installation & Repair", "Solar Panel Installation",
      "Cabinet Making", "Woodworking", "Metalworking",
      "Blacksmithing", "Upholstery", "Carpet Cleaning",
      "Pressure Washing", "Junk Removal", "Moving Services",
      "Pest Control", "Landscaping", "Tree Service",
      "Pool Maintenance", "Chimney Sweeping",
      "Handyman Services", "Home Renovation",
    ],
  },
];

/**
 * Flat array of all skills (for dropdowns, filters, etc.)
 * Sorted alphabetically with "Other" at the end.
 */
export const ALL_SKILLS: string[] = [
  ...new Set(SKILL_CATEGORIES.flatMap((cat) => cat.skills)),
].sort((a, b) => a.localeCompare(b));

ALL_SKILLS.push("Other");

/**
 * Legacy flat array (backward-compatible name used across the codebase)
 */
export const categories = ALL_SKILLS;

/**
 * Get the group/category name for a given skill
 */
export function getSkillGroup(skill: string): string {
  for (const cat of SKILL_CATEGORIES) {
    if (cat.skills.includes(skill)) return cat.group;
  }
  return "Other";
}

/**
 * Search/filter skills by query string
 */
export function searchSkills(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_SKILLS;
  return ALL_SKILLS.filter(
    (s) =>
      s.toLowerCase().includes(q) ||
      getSkillGroup(s).toLowerCase().includes(q)
  );
}

/**
 * Specific technologies, tools, and frameworks (for Post Job skill picker)
 */
export const TECH_SKILLS: string[] = [
  // Web/Frontend
  "HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Vue.js", "Nuxt.js",
  "Angular", "Svelte", "SvelteKit", "Remix", "Astro", "Redux", "Tailwind CSS",
  "Bootstrap", "Material UI", "Chakra UI", "Ant Design", "Styled Components",
  "Web3.js", "Solid.js", "Three.js", "D3.js", "GSAP",
  // Backend
  "Node.js", "Express", "NestJS", "Fastify", "Python", "Django", "Flask", "FastAPI",
  "Ruby on Rails", "PHP", "Laravel", "Symfony", "Go", "Java", "Spring Boot",
  "C#", ".NET Core", "ASP.NET", "C++", "C", "Rust", "Elixir", "Phoenix",
  "GraphQL", "REST API", "gRPC", "tRPC", "Socket.IO",
  // Mobile
  "React Native", "Flutter", "Android (Kotlin)", "Android (Java)",
  "iOS (Swift)", "SwiftUI", "Jetpack Compose", "Ionic", "Xamarin",
  // Data/ML/AI
  "SQL", "NoSQL", "MongoDB", "PostgreSQL", "MySQL", "MariaDB", "Redis",
  "Elasticsearch", "Firebase", "Supabase", "DynamoDB", "Cassandra", "Neo4j",
  "Pandas", "NumPy", "Scikit-learn", "TensorFlow", "PyTorch", "Keras",
  "Apache Spark", "Hadoop", "Tableau", "Power BI",
  "OpenAI API", "LangChain", "Hugging Face", "Stable Diffusion",
  "AI Prompt Engineering", "Machine Learning", "Deep Learning",
  "Natural Language Processing (NLP)", "Computer Vision",
  "Data Engineering", "Big Data", "R", "MATLAB", "Jupyter",
  // DevOps/Cloud
  "Docker", "Kubernetes", "CI/CD", "GitHub Actions", "GitLab CI", "Jenkins",
  "CircleCI", "AWS", "Azure", "GCP", "DigitalOcean", "Vercel", "Netlify",
  "Terraform", "Ansible", "Pulumi", "Linux", "Nginx", "Apache",
  "Serverless", "AWS Lambda", "Prometheus", "Grafana", "Datadog",
  "Git", "GitHub", "GitLab",
  // Design/Creative
  "UI/UX Design", "Figma", "Adobe XD", "Sketch", "Photoshop", "Illustrator",
  "After Effects", "Premiere Pro", "InDesign", "Canva", "Graphic Design",
  "Motion Graphics", "3D Modeling", "Blender", "Maya", "Cinema 4D", "ZBrush",
  "Video Editing", "Photography", "Videography", "DaVinci Resolve",
  "Lightroom", "Framer", "InVision",
  // Writing/Content
  "Content Writing", "Copywriting", "Technical Writing", "Blog Writing",
  "Creative Writing", "Editing & Proofreading", "SEO Writing", "Ghostwriting",
  "Translation", "Transcription", "Grant Writing", "Scriptwriting",
  // Marketing/Business
  "SEO", "SEM", "Google Ads", "Facebook Ads", "Social Media Management",
  "Email Marketing", "Marketing Automation", "Growth Hacking",
  "Project Management", "Agile/Scrum", "Scrum Master", "Product Management",
  "Sales", "Lead Generation", "Customer Success", "HubSpot", "Salesforce",
  "CRM", "Business Analysis", "Financial Modeling", "Market Research",
  // Security/Blockchain
  "Cybersecurity", "Ethical Hacking", "Penetration Testing",
  "Information Security", "Network Security",
  "Blockchain", "Smart Contracts", "Solidity", "Solana", "Ethereum",
  "Web3 Development", "DeFi", "NFT Development",
  // QA/Testing
  "QA/Testing", "Automated Testing", "Selenium", "Cypress", "Playwright",
  "Jest", "Mocha", "Testing Library", "Performance Testing", "Load Testing",
  // Other/Specialized
  "Game Development", "Unity", "Unreal Engine", "Godot",
  "Excel/VBA", "Virtual Assistant", "Data Entry", "Customer Support",
  "IoT", "Arduino", "Raspberry Pi", "Robotics",
  "AutoCAD", "SolidWorks", "Revit", "SketchUp",
  "QuickBooks", "Xero", "SAP",
  "Other",
];

/**
 * Combined list: categories + tech skills (deduplicated, sorted)
 * Use this for Post Job and any form that needs a comprehensive skill picker.
 */
export const ALL_SKILLS_WITH_TECH: string[] = [
  ...new Set([...ALL_SKILLS, ...TECH_SKILLS]),
].sort((a, b) => {
  if (a === "Other") return 1;
  if (b === "Other") return -1;
  return a.localeCompare(b);
});
