const mongoose = require('mongoose');

const blogSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },
  content: {
    type: String,
    required: true
  },
  category: {
    type: String,
    required: true,
    enum: [
      'Technology',
      'Design',
      'Business',
      'Lifestyle',
      'Tutorial',
      'News',
      'AI & Machine Learning',
      'Data Science',
      'Programming',
      'Product',
      'Startups',
      'Marketing',
      'Remote Work',
      'Education',
      'Health',
      'Finance',
      'Case Study',
      'Interview',
      'Opinion',
      'Guides',
      'Announcements',
      'Food & Cooking',
      'Drinks & Beverages',
      'Media & Entertainment',
      'Sports & Fitness',
      'Travel',
      'Photography',
      'Music',
      'Movies & TV',
      'Gaming',
      'Fashion & Beauty',
      'Parenting',
      'Relationships',
      'Personal Development',
      'Environment & Sustainability',
      'Politics',
      'Science',
      'Books & Literature',
      'Automotive',
      'Real Estate',
      'Cryptocurrency',
      'Web3 & Blockchain',
      'Art & Creativity',
      'Pets & Animals',
      'DIY & Crafts',
      'Home & Garden',
      'Career Development',
      'Productivity',
      'Mental Health',
      'Wellness & Spa',
      'Entrepreneurship',
      'Social Media',
      'E-commerce',
      'SaaS',
      'Mobile Apps',
      'Cloud Computing',
      'Cybersecurity',
      'DevOps',
      'UX/UI Design',
      'Content Writing',
      'SEO & Analytics',
      'Video Production',
      'Podcasting',
      'Freelancing',
      'Culture & Society',
      'History',
      'Philosophy',
      'Religion & Spirituality',
      'Law & Legal',
      'Architecture',
      'Interior Design',
      'Agriculture & Farming',
      'Economics',
      'Psychology',
      'Meditation & Mindfulness',
      'Yoga',
      'Nutrition & Diet',
      'Fitness Training',
      'Running & Marathon',
      'Cycling',
      'Swimming',
      'Martial Arts',
      'Dance',
      'Theater & Performing Arts',
      'Comedy',
      'Stand-up',
      'Craft Beer & Wine',
      'Coffee & Tea',
      'Street Food',
      'Vegan & Vegetarian',
      'Baking & Pastry',
      'BBQ & Grilling',
      'Seafood',
      'International Cuisine',
      'Desserts & Sweets',
      'Aviation & Aerospace',
      'Space & Astronomy',
      'Physics',
      'Chemistry',
      'Biology',
      'Medicine',
      'Nursing',
      'Pharmacy',
      'Dentistry',
      'Veterinary',
      'Marine Biology',
      'Geology',
      'Meteorology',
      'Robotics',
      'Engineering',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Civil Engineering',
      'Software Engineering',
      'Chemical Engineering',
      'Mathematics',
      'Statistics',
      'Quantum Computing',
      'Nanotechnology',
      'Biotechnology',
      'Genetics',
      'Neuroscience',
      'Investing & Stock Market',
      'Insurance',
      'Banking',
      'Trading & Forex',
      'Personal Finance',
      'Retirement Planning',
      'Tax Planning',
      'Accounting',
      'Auditing',
      'Nonprofit & Charity',
      'Human Rights',
      'Social Justice',
      'Immigration',
      'International Relations',
      'Military & Defense',
      'Public Policy',
      'Urban Planning',
      'Smart Cities',
      'Renewable Energy',
      'Solar Power',
      'Wind Energy',
      'Electric Vehicles',
      'Climate Change',
      'Conservation',
      'Wildlife',
      'Recycling & Waste Management',
      'Sustainable Living',
      'Zero Waste',
      'Minimalism',
      'Tiny Houses',
      'Van Life',
      'Digital Nomad',
      'Expat Living',
      'Study Abroad',
      'Language Learning',
      'Teaching & Tutoring',
      'Online Learning',
      'Higher Education',
      'Homeschooling',
      'Early Childhood Education',
      'Special Education',
      'STEM Education',
      'EdTech',
      'Competitive Exams',
      'Scholarships',
      'Student Life',
      'Greek Life',
      'College Sports',
      'Professional Sports',
      'Olympic Sports',
      'Fantasy Sports',
      'Sports Analytics',
      'Extreme Sports',
      'Adventure Travel',
      'Luxury Travel',
      'Budget Travel',
      'Solo Travel',
      'Family Travel',
      'Backpacking',
      'Camping & Hiking',
      'Beach & Ocean',
      'Mountain & Skiing',
      'Road Trips',
      'Cruises',
      'Hotels & Hospitality',
      'Airlines',
      'Travel Hacking',
      'Digital Photography',
      'Film Photography',
      'Portrait Photography',
      'Landscape Photography',
      'Wedding Photography',
      'Wildlife Photography',
      'Street Photography',
      'Drone Photography',
      'Mobile Photography',
      'Photo Editing',
      'Videography',
      'Animation',
      'Graphic Design',
      'Web Design',
      'Logo Design',
      'Typography',
      'Illustration',
      '3D Modeling',
      'Game Design',
      'Level Design',
      'Character Design',
      'Sound Design',
      'Music Production',
      'DJing',
      'Audio Engineering',
      'Songwriting',
      'Classical Music',
      'Rock & Metal',
      'Hip Hop & Rap',
      'Electronic & EDM',
      'Jazz & Blues',
      'Country & Folk',
      'K-Pop & J-Pop',
      'Latin Music',
      'Reggae',
      'Concert Reviews',
      'Music Festivals',
      'Indie Films',
      'Documentaries',
      'Anime',
      'TV Series Reviews',
      'Netflix & Streaming',
      'Film Criticism',
      'Screenwriting',
      'Acting',
      'Directing',
      'Cinematography',
      'PC Gaming',
      'Console Gaming',
      'Mobile Gaming',
      'Esports',
      'Game Reviews',
      'Gaming Hardware',
      'Retro Gaming',
      'Board Games',
      'Card Games',
      'Puzzle Games',
      'RPG',
      'FPS',
      'MOBA',
      'Battle Royale',
      'Simulation Games',
      'Strategy Games',
      'Indie Games'
    ]
  },
  readTime: {
    type: String,
    required: true
  },
  author: {
    type: String,
    default: 'Admin'
  },
  imageUrl: {
    type: String,
    default: null
  },
  likes: {
    type: Number,
    default: 0
  },
  comments: {
    type: Number,
    default: 0
  },
  views: {
    type: Number,
    default: 0
  },
  isPublished: {
    type: Boolean,
    default: true
  }
}, {
  timestamps: true
});

// Index for better query performance
blogSchema.index({ category: 1, createdAt: -1 });
blogSchema.index({ title: 'text', content: 'text' });

module.exports = mongoose.model('Blog', blogSchema);
